### ISSUE TITLE
[ServiceGen] Issue with optional parameters

### ISSUE THREAD

**Issue by ayadio** [get-focus/kinetix-tools#4]
I have a service which takes an optional int like so:
```c#
public Dto SaveProposition(int id, int? numeroProposition)
```
The generated equivalent's type in TypeScript is number and not number|undefined
```typescript
export function SaveProposition(id: number, numeroProposition: number)
```

**Comment by JabX** [comment]
Je suppose que si tu as fermé c'est que tu as trouvé la solution, mais je vais quand même répondre. Le générateur vérifie s'il y a un `= null` pour vérifier que le paramètre est optionnel, pas le type. Déjà parce que c'est comme ça qu'on déclare un paramètre optionnel en C#, mais aussi parce qu'on ne pourrait pas savoir si c'était un string par exemple.

**Comment by ayadio** [comment]
Oui c'était ça, ce détail m'avait échappé. Merci pour l'explication ! :)
